#!/usr/bin/env bash
# retrovibe

# Generated using mkx 3.1.2: https://github.com/remino/mkx

VERSION='2.1.0'

retrovibe_main() {
	set -euo pipefail

	trap _exit INT TERM

	E_ARGS=16
	E_MISSING_APP=17
	E_MISSING_FILE=18
	E_NEED_ROOT=19

	SCRIPT_INV="$(basename "$0")"
	SCRIPT_PATH="$(readlink -f "$0")"
	SCRIPT_NAME="$(basename "$SCRIPT_PATH")"
	SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"

	SETUP_DIR="$SCRIPT_DIR/setup"
	VOL_A="$SCRIPT_DIR/a"
	VOL_B="$SCRIPT_DIR/b"

	while getopts hv OPT; do
		case $OPT in
			h) CMD=help ;;
			v) CMD=version ;;
			*) _invalid_opt ;;
		esac
	done

	shift "$((OPTIND - 1))"

	CMD=
	[ $# -gt 0 ] && [ -z "$CMD" ] && CMD="$1"
	[ $# -gt 0 ] && shift

	[ -z "$CMD" ] && CMD="help"

	case "$CMD" in
		clean | help | setup | start | version) "${SCRIPT_NAME}_$CMD" "$@" ;;
		*) _invalid_cmd ;;
	esac

	_exit
}

retrovibe_clean() {
	[ -d "$SETUP_DIR" ] && rm -fr "$SETUP_DIR"
}

retrovibe_help() {
	cat << USAGE
$SCRIPT_NAME $VERSION

USAGE: $SCRIPT_INV [<options>] <command> [<args>]

Code like it was 1994!

Manages a little PC VM with floppy drives using DOSBox-X that includes the 
Editor and QBasic from MS-DOS 6.22.

Requires 7z, curl, dosbox-x, mcopy, sha512sum, and unix2dos.

COMMANDS:

	clean
		Delete all setup files.

	setup
		Download MS-DOS 5.0 & 6.22 from WinWorld, if not downloaded already, verify
		checksum, then extract files.

	help
		Show this help screen.

	start
		Start DOSBox-X with A drive. (Requires 'setup' first.)

	version
		Show script name and version number.

OPTIONS:

	-h        Show this help screen.
	-v        Show script name and version number.

USAGE
}

retrovibe_setup() {
	_require 7z curl dosbox-x mcopy sha512sum unix2dos

	for i in "$SETUP_DIR" "$VOL_A" "$VOL_B"; do
		_echo "$i"
		[ ! -d "$i" ] && mkdir -p "$i"
	done

	_cd "$SETUP_DIR"

	_downloads | while read -r url file; do
		if [ ! -f "$file" ]; then
			curl -sL "$url" > "$file"
		fi
	done

	sha512sum -c "$SCRIPT_DIR/sha512sum"

	_extracted_dirs | while read -r dir name; do
		[ -d "$dir" ] && rm -fr "$dir"
		7z x -y "$dir.7z"
		mv "$name" "$dir"
	done

	_extract_files | while read -r disk file; do
		mcopy -n -i "$disk" ::/"$file" "$file"
	done

	_conf_expand > expand.conf
	dosbox-x -conf expand.conf -silent
	rm EXPAND.EXE

	_readme_txt | unix2dos > README.TXT

	mv -v *.BAS *.COM *.HLP *.EXE *.TXT "$VOL_A"
}

retrovibe_start() {
	_require dosbox-x
	_cd "$SCRIPT_DIR"
	dosbox-x
}

retrovibe_version() {
	_echo "$SCRIPT_NAME $VERSION"
}

_cd() {
	[ $# -lt 1 ] && _fatal $E_ARGS "Missing argument for _cd."
	cd "$1" || _fatal $E_CD_FAILED "Cannot change info directory: $1"
}

_conf_expand() {
	cat << CONF
[autoexec]
MOUNT C .
C:
EXPAND DOSSHELL.CO_ DOSSHELL.COM
EXPAND DOSSHELL.EX_ DOSSHELL.EXE
EXPAND DOSSHELL.HL_ DOSSHELL.HLP
EXPAND EDLIN.EX_ EDLIN.EXE
EXPAND EDIT.HL_ EDIT.HLP
EXPAND QBASIC.HL_ QBASIC.HLP
EXPAND MONEY.BA_ MONEY.BAS
EXPAND GORILLA.BA_ GORILLA.BAS
EXPAND NIBBLES.BA_ NIBBLES.BAS
EXPAND REMLINE.BA_ REMLINE.BAS
DEL DOSSHELL.CO_
DEL DOSSHELL.EX_
DEL DOSSHELL.HL_
DEL EDLIN.EX_
DEL EDIT.HL_
DEL QBASIC.HL_
DEL MONEY.BA_
DEL GORILLA.BA_
DEL NIBBLES.BA_
DEL REMLINE.BA_
CONF
}

_downloads() {
	cat << DL
https://winworldpc.com/download/49c3a35d-1245-0911-c3a7-c29d25525400/from/c3ae6ee2-8099-713d-3411-c3a6e280947e msdos500.7z
https://winworldpc.com/download/c38fc38d-68c2-bbe2-80a6-4b11c3a4c2ac/from/c3ae6ee2-8099-713d-3411-c3a6e280947e msdos622.7z
DL
}

_echo() {
	echo "$@"
}

_error() {
	_echo "$@" >&2
}

_exit() {
	exit_code=$?
	exit "$exit_code"
}

_extract_files() {
	cat << FILES
msdos500/Disk01.img EDLIN.EX_
msdos500/Disk02.img DOSSHELL.CO_
msdos500/Disk02.img DOSSHELL.EX_
msdos500/Disk02.img DOSSHELL.HL_
msdos500/Disk02.img MONEY.BA_
msdos500/Disk03.img GORILLA.BA_
msdos500/Disk03.img NIBBLES.BA_
msdos500/Disk03.img REMLINE.BA_
msdos622/Disk1.img EDIT.COM
msdos622/Disk1.img QBASIC.EXE
msdos622/Disk2.img EDIT.HL_
msdos622/Disk2.img QBASIC.HL_
msdos622/Suppdisk.img EXPAND.EXE
FILES
}

_extracted_dirs() {
	cat << DIRS
msdos500 Microsoft MS-DOS 5.00 (3.5-720k)
msdos622 Microsoft MS-DOS 6.22 Plus Enhanced Tools (3.5)
DIRS
}

_fatal() {
	exit_code="$1"
	shift
	_error "$@"
	exit "$exit_code"
}

_invalid_cmd() {
	_error "Invalid command: $CMD"
	_echo
	retrovibe_help
	exit "$E_ARGS"
}

_invalid_opt() {
	_error "Invalid option: $OPT"
	_echo
	retrovibe_help
	exit "$E_ARGS"
}

_require() {
	missing_bin=0

	for bin in "$@"; do
		if ! which "$bin" > /dev/null 2>&1; then
			missing_bin=1
			_error "Required: $bin"
		fi
	done

	if [ $missing_bin -ne 0 ]; then
		_fatal "$E_MISSING_APP" "One or more executables or apps are missing."
	fi
}

_require_root() {
	if [ "$EUID" -ne 0 ]; then
		_fatal $E_NEED_ROOT "Please run as root."
	fi
}

_readme_txt() {
	cat << BAT
 ____  _____ _____ ____   _____     _____ ____  _____ 
|  _ \| ____|_   _|  _ \ / _ \ \   / /_ _| __ )| ____|
| |_) |  _|   | | | |_) | | | \ \ / / | ||  _ \|  _|  
|  _ <| |___  | | |  _ <| |_| |\ V /  | || |_) | |___ 
|_| \_\_____| |_| |_| \_\\\___/  \_/  |___|____/|_____|
                                                      
Coding in 1994 was a vibe.
https://github.com/remino/retrovibe

EDIT     Start MS-DOS Editor.

EDLIN    Start Edlin.
DOSSHELL Start MS-DOS Shell.
QBASIC   Start MS-DOS QBasic.

DIR      List files.
HELP     Show help.
EXIT     Exit DOSBox-X.

BAT
}

retrovibe_main "$@"
